# -*- coding: utf-8 -*-
"""Videos 2025-I.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1o7KqahKX4s0DQlJ0dKnwXJaPTziZGpVw
"""

import streamlit as st
import pandas as pd

# Datos directamente en el código
datos = [
    {"FECHA": "04/03/2025", "GRUPO": 102, "UCA": "MÉTODOS CUANTITATIVOS", "LIGA": "https://drive.google.com/file/d/1ycqt5ItXi92Ie7f6SdNW_ySvW54l-o3k/view?usp=sharing"},
    {"FECHA": "05/03/2025", "GRUPO": 207, "UCA": "SISTEMAS CONTABLES DE INFORMACIÓN FINANCIERA", "LIGA": "https://drive.google.com/file/d/1xBvz3IEsfdzI1lVT-QGvUdBnw4myk6Dh/view?usp=sharing"},
    {"FECHA": "06/03/2025", "GRUPO": 103, "UCA": "MÉTODOS CUANTITATIVOS", "LIGA": "https://drive.google.com/file/d/1jdgtCbthjby2gSNg-dtm0SRBVS_AOeGZ/view?usp=sharing"},
    {"FECHA": "07/03/2025", "GRUPO": 101, "UCA": "MÉTODOS CUANTITATIVOS", "LIGA": "https://drive.google.com/file/d/1xPrNTa0vZWdqRJztG0X11WuVUmoUWLFS/view?usp=sharing"},
    {"FECHA": "08/03/2025", "GRUPO": 204, "UCA": "ESTADÍSTICA DESCRIPTIVA", "LIGA": "https://drive.google.com/file/d/1YJqV5aT77JF53dF_1N_8E6FW4sCUjPE7/view?usp=sharing"},
    {"FECHA": "13/03/2025", "GRUPO": 103, "UCA": "MÉTODOS CUANTITATIVOS", "LIGA": "https://drive.google.com/file/d/1T4QP9V6uzhgiSGkauzCDgMCHbRqsNp9L/view?usp=sharing"},
    {"FECHA": "14/03/2025", "GRUPO": 101, "UCA": "MÉTODOS CUANTITATIVOS", "LIGA": "https://drive.google.com/file/d/1PpNFYmt1IcLxF_eqj0xcI8b5AKDP_J2H/view?usp=sharing"},
    {"FECHA": "18/03/2025", "GRUPO": 102, "UCA": "MÉTODOS CUANTITATIVOS", "LIGA": "https://drive.google.com/file/d/1A5ZbcVODnC_2yNHlFeg0iH-uta4MrBEq/view?usp=sharing"},
    {"FECHA": "21/03/2025", "GRUPO": 101, "UCA": "MÉTODOS CUANTITATIVOS", "LIGA": "https://drive.google.com/file/d/1lmvb0KFkd9BlqC9CJ1hvsNJciDwx-Fm_/view?usp=sharing"},
    {"FECHA": "27/03/2025", "GRUPO": 103, "UCA": "MÉTODOS CUANTITATIVOS", "LIGA": "https://drive.google.com/file/d/1xS7s9cuWvXpySwYrGCd-uc5UXB3McCIG/view?usp=sharing"},
    {"FECHA": "03/04/2025", "GRUPO": 103, "UCA": "MÉTODOS CUANTITATIVOS", "LIGA": "https://drive.google.com/file/d/1pHp8T7vAJFPSfnW5D0M8sBdFsn1JiwiM/view?usp=sharing"},
]

# Convertir a DataFrame para facilitar el filtrado
df = pd.DataFrame(datos)

st.title("📚 Repositorio de Videos de Clase")
st.write("Selecciona tu grupo, fecha y materia para ver el video.")

# Menús de selección
grupo = st.selectbox("Selecciona tu grupo", sorted(df["GRUPO"].unique()))
fechas_filtradas = df[df["GRUPO"] == grupo]["FECHA"].unique()
fecha = st.selectbox("Selecciona la fecha", fechas_filtradas)

ucas_filtradas = df[(df["GRUPO"] == grupo) & (df["FECHA"] == fecha)]["UCA"].unique()
uca = st.selectbox("Selecciona la materia", ucas_filtradas)

# Filtrar resultados
video = df[(df["GRUPO"] == grupo) & (df["FECHA"] == fecha) & (df["UCA"] == uca)]

if not video.empty:
    liga = video.iloc[0]["LIGA"]
    st.success("¡Video encontrado!")

    # Convertir el enlace para previsualizar en iframe
    if "drive.google.com/file/d/" in liga:
        video_id = liga.split("/d/")[1].split("/")[0]
        embed_url = f"https://drive.google.com/file/d/{video_id}/preview"
        st.components.v1.iframe(embed_url, height=480)
    else:
        st.write(f"[Ver video en una nueva pestaña]({liga})")
else:
    st.warning("No se encontró un video con esos criterios.")