# -*- coding: utf-8 -*-
"""Videos 2025-I.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1o7KqahKX4s0DQlJ0dKnwXJaPTziZGpVw
"""

import streamlit as st
import pandas as pd

# Datos directamente en el código
datos = [
{"FECHA": "04/03/2026", "GRUPO": "409-GAM", "UCA": "LABORATORIO DE INNOVACIÓN SOCIAL", "LIGA": "https://drive.google.com/file/d/1s0XXophM_3qSHNuWFkIrYBZ0FHshKhl2/view?usp=sharing"},
{"FECHA": "05/03/2026", "GRUPO": "403-COY", "UCA": "FINANZAS BÁSICAS", "LIGA": "https://drive.google.com/file/d/1Em6-1KmTt26oQNBG4BWOFUKSzYq9gpmt/view?usp=sharing"},
{"FECHA": "05/03/2026", "GRUPO": "406-COY", "UCA": "INVESTIGACIÓN DE OPERACIONES", "LIGA": "https://drive.google.com/file/d/1sflNu09VvxTwHZvlSVZ1wIjWkQMZc1zD/view?usp=sharing"},
{"FECHA": "09/03/2023", "GRUPO": "404-UST", "UCA": "INVESTIGACIÓN DE OPERACIONES", "LIGA": "https://drive.google.com/file/d/1GO0Hn5eKStYjYxqGtLRbAbe6arLUgLGk/view?usp=sharing"},
{"FECHA": "09/03/2023", "GRUPO": "304-UST", "UCA": "PROBABILIDAD", "LIGA": "https://drive.google.com/file/d/1-GBqWLMHgPA9SuoMfamnjTxWGPN8GdSs/view?usp=sharing"},
{"FECHA": "11/03/2026", "GRUPO": "409-GAM", "UCA": "LABORATORIO DE INNOVACIÓN SOCIAL", "LIGA": "https://drive.google.com/file/d/12fSvx5TXB_gO_dqlSKR92HaO4HGn_VXh/view?usp=sharing"},
{"FECHA": "12/03/2026", "GRUPO": "403-COY", "UCA": "FINANZAS BÁSICAS", "LIGA": "https://drive.google.com/file/d/1L6E8S7JzlV7ueRkJZOhdG_WoInoL5jfe/view?usp=sharing"},
{"FECHA": "12/03/2026", "GRUPO": "406-COY", "UCA": "INVESTIGACIÓN DE OPERACIONES", "LIGA": "https://drive.google.com/file/d/1_CHNWp5vL_o2rFlUj_ziio_NQMIrY0Tu/view?usp=sharing"},
{"FECHA": "18/03/2026", "GRUPO": "409-GAM", "UCA": "LABORATORIO DE INNOVACIÓN SOCIAL", "LIGA": "https://drive.google.com/file/d/1EIXSr_p1WTM3H-OljmrlP_w9oVNrbW70/view?usp=sharing"},
{"FECHA": "19/03/2026", "GRUPO": "403-COY", "UCA": "FINANZAS BÁSICAS", "LIGA": "https://drive.google.com/file/d/1I3yzPe-NtcnNdf9IK649wF3e4f56D2qL/view?usp=sharing"},
{"FECHA": "19/03/2026", "GRUPO": "406-COY", "UCA": "INVESTIGACIÓN DE OPERACIONES", "LIGA": "https://drive.google.com/file/d/14FU-PPcy7nslokFbsqi_GU1FCoDDLKA5/view?usp=sharing"},
{"FECHA": "23/03/2026", "GRUPO": "404-UST", "UCA": "INVESTIGACIÓN DE OPERACIONES", "LIGA": "https://drive.google.com/file/d/1L1iDex468ffeopqyB2mSF-FuxSHYXlit/view?usp=sharing"},
{"FECHA": "23/03/2026", "GRUPO": "304-UST", "UCA": "PROBABILIDAD", "LIGA": "https://drive.google.com/file/d/1VWIFeGxRq6cRI-u9xamAIaf2x3CZG9TZ/view?usp=sharing"},
{"FECHA": "25/03/2026", "GRUPO": "409-GAM", "UCA": "LABORATORIO DE INNOVACIÓN SOCIAL", "LIGA": "https://drive.google.com/file/d/1VrbDs6X3OoBTmbcUR9SPjZqjJdwQz-R2/view?usp=sharing"},
{"FECHA": "26/03/2026", "GRUPO": "403-COY", "UCA": "FINANZAS BÁSICAS", "LIGA": "https://drive.google.com/file/d/1kKlJn_09aMDqr-zxfJD2N-TSLO61l1-_/view?usp=sharing"},
{"FECHA": "26/03/2026", "GRUPO": "406-COY", "UCA": "INVESTIGACIÓN DE OPERACIONES", "LIGA": "https://drive.google.com/file/d/1walmC-mFdfUFjKVulkY-Tyx4_CbkJ1Xv/view?usp=sharing"},
{"FECHA": "30/03/2026", "GRUPO": "404-UST", "UCA": "INVESTIGACIÓN DE OPERACIONES", "LIGA": "https://drive.google.com/file/d/1FPTejifQrYOSUU_TaTarhSi-lX27Y7sG/view?usp=sharing"},
{"FECHA": "30/03/2026", "GRUPO": "304-UST", "UCA": "PROBABILIDAD", "LIGA": "https://drive.google.com/file/d/1_gQwz8QmzJhpY-hbAcu7tgcBkBV34sHd/view?usp=sharing"},
{"FECHA": "01/04/2026", "GRUPO": "409-GAM", "UCA": "LABORATORIO DE INNOVACIÓN SOCIAL", "LIGA": "https://drive.google.com/file/d/1eSy9NMDGTKlsGsR83fXWwbK4D-PTIuLD/view?usp=sharing"},  
{"FECHA": "06/04/2026", "GRUPO": "404-UST", "UCA": "INVESTIGACIÓN DE OPERACIONES", "LIGA": "https://drive.google.com/file/d/1CbnaNO2F1j9OeDs_ZTbenO0_D2Ek8gSf/view?usp=sharing"},
{"FECHA": "06/04/2026", "GRUPO": "304-UST", "UCA": "PROBABILIDAD", "LIGA": "https://drive.google.com/file/d/1cpRPKMC4flu7RH0F3CS8aP0ybLETGO-l/view?usp=sharing"},
{"FECHA": "08/04/2026", "GRUPO": "409-GAM", "UCA": "LABORATORIO DE INNOVACIÓN SOCIAL", "LIGA": "https://drive.google.com/file/d/1vZDToZszByilcoGZuHWypW6rXWx1_M5c/view?usp=sharing"},
{"FECHA": "09/04/2026", "GRUPO": "406-COY", "UCA": "INVESTIGACIÓN DE OPERACIONES", "LIGA": "https://drive.google.com/file/d/1St-MgDZPx1OiH2bSJAvbHnGkLGofEoo7/view?usp=sharing"},
{"FECHA": "13/04/2026", "GRUPO": "404-UST", "UCA": "INVESTIGACIÓN DE OPERACIONES", "LIGA": "https://drive.google.com/file/d/1QlSzT1_5LXVlPwHp9uBRzJ5lxQtu-fYh/view?usp=sharing"},
{"FECHA": "13/04/2026", "GRUPO": "304-UST", "UCA": "PROBABILIDAD", "LIGA": "https://drive.google.com/file/d/13ZVEu-fhqXYqE5hk97CUtwKYRVK-_GvF/view?usp=sharing"},
{"FECHA": "15/04/2026", "GRUPO": "409-GAM", "UCA": "LABORATORIO DE INNOVACIÓN SOCIAL", "LIGA": "https://drive.google.com/file/d/1cOPlfIRFpFLgO31uz9d6a9R7Z4M3ou8l/view?usp=sharing"},
{"FECHA": "16/04/2026", "GRUPO": "403-COY", "UCA": "FINANZAS BÁSICAS", "LIGA": "https://drive.google.com/file/d/1oP_F2vYPv6ug0ZsXEo2OJj8URSLh2Oc_/view?usp=sharing"},
{"FECHA": "16/04/2026", "GRUPO": "406-COY", "UCA": "INVESTIGACIÓN DE OPERACIONES", "LIGA": "https://drive.google.com/file/d/1MVCkcd_uhDbP-rKAPLfcsO-g2QXtx5j-/view?usp=sharing"},
{"FECHA": "22/04/2026", "GRUPO": "409-GAM", "UCA": "LABORATORIO DE INNOVACIÓN SOCIAL", "LIGA": "https://drive.google.com/file/d/1YAeV4QYXWUEiUmgAiewco1U0zgp2KyNY/view?usp=sharing"},
{"FECHA": "23/04/2026", "GRUPO": "403-COY", "UCA": "FINANZAS BÁSICAS", "LIGA": "https://drive.google.com/file/d/1q86V-JXUX9_Xz-vLc8i9FCn7vWdp6M14/view?usp=sharing"},
{"FECHA": "23/04/2026", "GRUPO": "406-COY", "UCA": "INVESTIGACIÓN DE OPERACIONES", "LIGA": "https://drive.google.com/file/d/1YurlaGocWVKVgYHyKSoRQEyShKh1gcas/view?usp=sharing"},
{"FECHA": "27/04/2026", "GRUPO": "404-UST", "UCA": "INVESTIGACIÓN DE OPERACIONES", "LIGA": "https://drive.google.com/file/d/1ztsN-0zP-Vcd9eFSTbpUCvh03RC0yW5L/view?usp=sharing"},
{"FECHA": "27/04/2026", "GRUPO": "304-UST", "UCA": "PROBABILIDAD", "LIGA": "https://drive.google.com/file/d/1iqcOqHm_nAtfNumRp6TjsVgVYf6Sav5e/view?usp=sharing"},
{"FECHA": "29/04/2026", "GRUPO": "409-GAM", "UCA": "LABORATORIO DE INNOVACIÓN SOCIAL", "LIGA": "https://drive.google.com/file/d/1KuwFAprUj6qbBi1cRyddc59mq2gyuUNP/view?usp=sharing"},
{"FECHA": "30/04/2026", "GRUPO": "403-COY", "UCA": "FINANZAS BÁSICAS", "LIGA": "https://drive.google.com/file/d/18kv8ATX8LNkhIilSPMervH_G0gzBTn_b/view?usp=sharing"},
{"FECHA": "30/04/2026", "GRUPO": "406-COY", "UCA": "INVESTIGACIÓN DE OPERACIONES", "LIGA": "https://drive.google.com/file/d/1-2HtA6U6yQ5OZzVl4zHu3gzqBhETbitw/view?usp=sharing"},
{"FECHA": "02/05/2026", "GRUPO": "409-GAM", "UCA": "LABORATORIO DE INNOVACIÓN SOCIAL", "LIGA": "https://drive.google.com/file/d/1nNQpKO28c1S-wOs1wnRRg9ZXrH_ZhTpN/view?usp=sharing"},
{"FECHA": "04/05/2026", "GRUPO": "404-UST", "UCA": "INVESTIGACIÓN DE OPERACIONES", "LIGA": "https://drive.google.com/file/d/16x-FigLOqEckmkqhzJcugiI-ieXKrnAL/view?usp=sharing"},
{"FECHA": "04/05/2026", "GRUPO": "304-UST", "UCA": "PROBABILIDAD", "LIGA": "https://drive.google.com/file/d/15ifpiopOusKj83apE1klFetA6uZZXMUf/view?usp=sharing"},
{"FECHA": "06/05/2026", "GRUPO": "409-GAM", "UCA": "LABORATORIO DE INNOVACIÓN SOCIAL", "LIGA": "https://drive.google.com/file/d/10nl5YZtPqxfGPJtEdp8dR6ppb0s-Cx9k/view?usp=sharing"},
{"FECHA": "07/05/2026", "GRUPO": "403-COY", "UCA": "FINANZAS BÁSICAS", "LIGA": "https://drive.google.com/file/d/1a2QhVekBXnYQzpSRHHeZEPCINhhnehIQ/view?usp=sharing"},
{"FECHA": "07/05/2026", "GRUPO": "406-COY", "UCA": "INVESTIGACIÓN DE OPERACIONES", "LIGA": "https://drive.google.com/file/d/10WaEykGwUhViKqjv_i9HTpsqEe6DyVp-/view?usp=sharing"},
{"FECHA": "11/05/2026", "GRUPO": "404-UST", "UCA": "INVESTIGACIÓN DE OPERACIONES", "LIGA": "https://drive.google.com/file/d/1yMVWxhs2bnLoXJcsNdd2ttvEdIG7t2gp/view?usp=sharing"},
{"FECHA": "11/05/2026", "GRUPO": "304-UST", "UCA": "PROBABILIDAD", "LIGA": "https://drive.google.com/file/d/1PoDO0gGWTWBpJ0zHBtpX_hPzG5PPc3XE/view?usp=sharing"},
{"FECHA": "13/05/2026", "GRUPO": "409-GAM", "UCA": "LABORATORIO DE INNOVACIÓN SOCIAL", "LIGA": "https://drive.google.com/file/d/1j2FaMM_0H94XEQX2nBHz667FXVtQk3Fv/view?usp=sharing"},
{"FECHA": "14/05/2026", "GRUPO": "403-COY", "UCA": "FINANZAS BÁSICAS", "LIGA": "https://drive.google.com/file/d/1caJG6E9AJZb8X5uBwxSQr38CWggXqxmP/view?usp=sharing"},
{"FECHA": "14/05/2026", "GRUPO": "406-COY", "UCA": "INVESTIGACIÓN DE OPERACIONES", "LIGA": "https://drive.google.com/file/d/198nEFv9qAH8VEuA46H7Ehxlmtxzafp7R/view?usp=sharing"},
{"FECHA": "18/05/2026", "GRUPO": "404-UST", "UCA": "INVESTIGACIÓN DE OPERACIONES", "LIGA": "https://drive.google.com/file/d/1R16dr314Mt63JsgwEnSRwxneJxIprJI6/view?usp=sharing"},
{"FECHA": "18/05/2026", "GRUPO": "304-UST", "UCA": "PROBABILIDAD", "LIGA": "https://drive.google.com/file/d/1RVRy9TI4mktBTtvAzh8v76FnnLlSLcXL/view?usp=sharing"},
{"FECHA": "20/05/2026", "GRUPO": "409-GAM", "UCA": "LABORATORIO DE INNOVACIÓN SOCIAL", "LIGA": "https://drive.google.com/file/d/1-0akLwY8uxOBSxx5OfYvt40ZyKSUecAX/view?usp=sharing"},
{"FECHA": "21/05/2026", "GRUPO": "403-COY", "UCA": "FINANZAS BÁSICAS", "LIGA": "https://drive.google.com/file/d/1jeqZ6GHpEqDM-uu4uodL712jgw3irTql/view?usp=sharing"},
{"FECHA": "21/05/2026", "GRUPO": "406-COY", "UCA": "INVESTIGACIÓN DE OPERACIONES", "LIGA": "https://drive.google.com/file/d/1BMx9FhgXYr1_5hdAk1nHGjb9LGMkZhQ3/view?usp=sharing"},
]

# Convertir a DataFrame para facilitar el filtrado
df = pd.DataFrame(datos)
st.image("UNRC.png", caption="Universidad Nacional Rosario Castellanos", width=300)
st.title("Repositorio de Videos de Clase")
st.write("Selecciona tu grupo, fecha y materia para ver el video.")

# Menús de selección
grupo = st.selectbox("Selecciona tu grupo", sorted(df["GRUPO"].unique()))
fechas_filtradas = df[df["GRUPO"] == grupo]["FECHA"].unique()
fecha = st.selectbox("Selecciona la fecha", fechas_filtradas)

ucas_filtradas = df[(df["GRUPO"] == grupo) & (df["FECHA"] == fecha)]["UCA"].unique()
uca = st.selectbox("Selecciona la materia", ucas_filtradas)

# Filtrar resultados
video = df[(df["GRUPO"] == grupo) & (df["FECHA"] == fecha) & (df["UCA"] == uca)]

if not video.empty:
    liga = video.iloc[0]["LIGA"]
    st.success("¡Video encontrado!")

    # Convertir el enlace para previsualizar en iframe
    if "drive.google.com/file/d/" in liga:
        video_id = liga.split("/d/")[1].split("/")[0]
        embed_url = f"https://drive.google.com/file/d/{video_id}/preview"
        st.components.v1.iframe(embed_url, height=480)
    else:
        st.write(f"[Ver video en una nueva pestaña]({liga})")
else:
    st.warning("No se encontró un video con esos criterios.")
