# -*- coding: utf-8 -*-
"""Videos 2025-I.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1o7KqahKX4s0DQlJ0dKnwXJaPTziZGpVw
"""

import streamlit as st
import pandas as pd

# Datos directamente en el código
datos = [
{"FECHA": "08/09/2025", "GRUPO": 303, "UCA": "PROBABILIDAD", "LIGA": "https://drive.google.com/file/d/1VfQGYwMuwj1_zQYv3pyD-cNSsFsmeckn/view?usp=sharing"},
{"FECHA": "08/09/2025", "GRUPO": 307, "UCA": "PROBABILIDAD", "LIGA": "https://drive.google.com/file/d/1dABcCqjhoV6fmrM9jS89TqAE2Xq360XH/view?usp=sharing"},
{"FECHA": "11/09/2025", "GRUPO": 302, "UCA": "PROBABILIDAD", "LIGA": "https://drive.google.com/file/d/1wqnwKw15SxaDMZ-Qbccp3EMNLSCxU1ml/view?usp=sharing"},
{"FECHA": "13/09/2025", "GRUPO": 301, "UCA": "PROBABILIDAD", "LIGA": "https://drive.google.com/file/d/1o2fZ1oRrcVlsv6SEdCS6937N6PIRo0pj/view?usp=sharing"},
{"FECHA": "13/09/2025", "GRUPO": 201, "UCA": "DESARROLLO SOSTENIBLE, EQUIDAD Y RESPONSABILIDAD SOCIAL", "LIGA": "https://drive.google.com/file/d/1OTle2VldIgSFRoGs1Lnrv8jziDH4UdHW/view?usp=sharing"},
{"FECHA": "15/09/2025", "GRUPO": 303, "UCA": "PROBABILIDAD", "LIGA": "https://drive.google.com/file/d/1wJ5bc3cllUexEz7X7LnhFyc0VuaLnj9j/view?usp=sharing"},
{"FECHA": "15/09/2025", "GRUPO": 307, "UCA": "PROBABILIDAD", "LIGA": "https://drive.google.com/file/d/13Qt3WOV6KycOHsqKnHPKUqEzdwwJk4zg/view?usp=sharing"},
{"FECHA": "18/09/2025", "GRUPO": 302, "UCA": "PROBABILIDAD", "LIGA": "https://drive.google.com/file/d/1-v8qw96IvY2faFteH8ILBP9gYlyTHxaZ/view?usp=sharing"},
{"FECHA": "22/09/2025", "GRUPO": 303, "UCA": "PROBABILIDAD", "LIGA": "https://drive.google.com/file/d/1iCwZySIt5dBy61ZUAUyPLuHau6XzyF0z/view?usp=sharing"},
{"FECHA": "22/09/2025", "GRUPO": 307, "UCA": "PROBABILIDAD", "LIGA": "https://drive.google.com/file/d/1NTZLt-dsg6qGHxi8nUEhHx2ShwPieuXI/view?usp=sharing"},
{"FECHA": "25/09/2025", "GRUPO": 302, "UCA": "PROBABILIDAD", "LIGA": "https://drive.google.com/file/d/1tRMfA9RNsuPiKQ6NoZCPa4opEOzwUAiA/view?usp=sharing"},
{"FECHA": "27/09/2025", "GRUPO": 301, "UCA": "PROBABILIDAD", "LIGA": "https://drive.google.com/file/d/1Inmz9JYiBzbq8-70dhY7-4gCqAQ3R3Yw/view?usp=sharing"},
{"FECHA": "27/09/2025", "GRUPO": 201, "UCA": "DESARROLLO SOSTENIBLE, EQUIDAD Y RESPONSABILIDAD SOCIAL", "LIGA": "https://drive.google.com/file/d/1bxXggzEBw5FeCncRIxY26IkOJ_DOaJJz/view?usp=sharing"},
{"FECHA": "29/09/2025", "GRUPO": 303, "UCA": "PROBABILIDAD", "LIGA": "https://drive.google.com/file/d/1gNG9L5aYNUXazi_r2AW2DlXSWymQPxiq/view?usp=sharing"},
{"FECHA": "29/09/2025", "GRUPO": 307, "UCA": "PROBABILIDAD", "LIGA": "https://drive.google.com/file/d/16W5dmLnu_41_GXmkJvAGjX5cBeDnLokx/view?usp=sharing"},

]

# Convertir a DataFrame para facilitar el filtrado
df = pd.DataFrame(datos)
st.image("UNRC.png", caption="Universidad Nacional Rosario Castellanos", width=550)
st.title("Repositorio de Videos de Clase")
st.write("Selecciona tu grupo, fecha y materia para ver el video.")

# Menús de selección
grupo = st.selectbox("Selecciona tu grupo", sorted(df["GRUPO"].unique()))
fechas_filtradas = df[df["GRUPO"] == grupo]["FECHA"].unique()
fecha = st.selectbox("Selecciona la fecha", fechas_filtradas)

ucas_filtradas = df[(df["GRUPO"] == grupo) & (df["FECHA"] == fecha)]["UCA"].unique()
uca = st.selectbox("Selecciona la materia", ucas_filtradas)

# Filtrar resultados
video = df[(df["GRUPO"] == grupo) & (df["FECHA"] == fecha) & (df["UCA"] == uca)]

if not video.empty:
    liga = video.iloc[0]["LIGA"]
    st.success("¡Video encontrado!")

    # Convertir el enlace para previsualizar en iframe
    if "drive.google.com/file/d/" in liga:
        video_id = liga.split("/d/")[1].split("/")[0]
        embed_url = f"https://drive.google.com/file/d/{video_id}/preview"
        st.components.v1.iframe(embed_url, height=480)
    else:
        st.write(f"[Ver video en una nueva pestaña]({liga})")
else:
    st.warning("No se encontró un video con esos criterios.")